### ISSUE TITLE
DaggerAppComponent missing

### ISSUE THREAD

**Issue by nicopasso** [frogermcs/GithubClient#1]
Hi,
in GithubClientApplication.java file there's the creation of the global dependencies graph

``` java
DaggerAppComponent.builder()
     .appModule(new AppModule(this))
     .githubApiModule(new GithubApiModule())
     .build();
```

But where is the DaggerAppComponent class in the project? I couldn't find it. I'm missing something?

Thanks
Nico

**Comment by frogermcs** [comment]
Hey,

This class is automatically generated by Dagger lib in compile time. Try to build app and you should see Dagger\* classes.

**Comment by nicopasso** [comment]
Ok thanks for the explanation :+1:
