### ISSUE TITLE
UserComponent release

### ISSUE THREAD

**Issue by legarspol** [frogermcs/GithubClient#2]
Hi !

First congrats for you tuto, thank you for sharing your knowledge with us.
Why didn't you committed the userComponent release logic as described in this gist in the repository ?
https://gist.github.com/frogermcs/f1d0c916d91d1a341e4a#file-githubclientapplication-java

I am interested in when you actually call that releaseUserComponent method.

**Comment by frogermcs** [comment]
Well, I think there is no logic. UserComponent reference is set to null in GithubClientApplication class.

And releaseUserComponent() call is done here: https://github.com/frogermcs/GithubClient/blob/master/app/src/main/java/frogermcs/io/githubclient/ui/activity/RepositoriesListActivity.java#L79

In moment when we're finishing RepositoriesListActivity.

**Comment by legarspol** [comment]
My bad. I still had an old version of your code where that line weren't there.
Thanks for your answer!
